repos:
-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: v1.2.1-1
    hooks:
    -   id: check-case-conflict
    -   id: check-executables-have-shebangs
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: check-xml
    -   id: check-yaml
    -   id: detect-private-key
    -   id: end-of-file-fixer
    -   id: file-contents-sorter
        files: .gitignore
    -   id: trailing-whitespace
    -   id: check-ast
    -   id: double-quote-string-fixer
    -   id: debug-statements
    -   id: name-tests-test
    -   id: requirements-txt-fixer
-   repo: git://github.com/pre-commit/mirrors-pylint
    sha: v1.8.2
    hooks:
    -   id: pylint
        args:
        - -d abstract-method  # TODO: implement full ESL code for Asp and Bot
        - -d duplicate-code
        - -d fixme
        - -d import-error
        - -d invalid-name
        - -d locally-disabled
        - -d missing-docstring
        - -d protected-access  # TODO: switchy addHandler breaks
        - -d too-few-public-methods
        - -d too-many-arguments
